[package]
name = "hd-spike"
version = "0.0.1"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = { version = "0.11.2", default-features = false, features = ["cpi", "copy"] }
pinocchio-system = "0.6.1"

[target.'cfg(not(target_os = "solana"))'.dependencies]
solana-address = { version = "2.7", features = ["curve25519"] }
