"""Renders planner/RESULTS.md from the evaluation summary (generated; do not edit by hand)."""
from __future__ import annotations

import math
from typing import Dict, List

from . import archetypes as ar

NAMES = {
    "prior": "population prior only",
    "pooled": "per-slot posterior, no day-of-week",
    "beta_dow": "**Beta-Bernoulli + day-of-week (ships)**",
    "gbdt": "GBDT on lag features (optional comparator)",
    "fixed_23_07": "fixed 23:00-07:00",
    "yesterday": "yesterday's idle block",
}


def _f(v, d=3):
    return "n/a" if v is None or (isinstance(v, float) and math.isnan(v)) else f"{v:.{d}f}"


def _p(v, d=1):
    return "n/a" if v is None or (isinstance(v, float) and math.isnan(v)) else f"{100 * v:.{d}f}%"


def render(S: Dict) -> str:
    L: List[str] = []
    L.append("# Shift Planner: results (generated by `python -m planner.evaluate`)\n")
    L.append("> **Synthetic users only.** Five archetypes simulated minute by minute and written out as the exact "
             "log events the app records (LOG_SCHEMA.md). Real users are messier; these numbers show the model is "
             "calibrated and useful on plausible rhythms, not that it is on yours.\n")
    sz = S["sizes"]
    L.append(f"Protocol: every simulated day at 18:00 the planner sees only the logs written so far and forecasts "
             f"the next 96 slots (24 h); days 0-{S['warmup_days'] - 1} are warm-up (see the cold-start table). "
             f"Tuning population {sz['tune']} users and test population {sz['test']} users ({sz['per_archetype']} per "
             f"archetype each, disjoint seeds), {sz['days']} days each. Everything below is the test population.\n")
    p = S["params"]
    L.append("## Chosen parameters (tuned on the tuning population only)\n")
    rule = (f"survival rule (maximize length x prod(p)^{p['window_gamma']}, runs start and end on slots with "
            f"p >= {p['window_threshold']})" if p["window_rule"] == "survival"
            else f"Kadane rule (maximize the sum of p - {p['window_threshold']})")
    L.append(f"Half-life {p['half_life_days']} days; shrinkage k0 = {p['k0']}, k1 = {p['k1']}, k2 = {p['k2']}; slot "
             f"kernel {p['kernel']}; window: {rule}, at least {p['min_window_slots'] * 15} min, ending by the next "
             f"alarm; auto-arm when every slot's lower bound (z = {p['auto_arm_z']}) is >= "
             f"{p['auto_arm_threshold']} after {p['auto_arm_min_nights']} nights"
             f"{' (1.0 = off: no bar met the completion target on the tuning population)' if p['auto_arm_threshold'] >= 1.0 else ''}. "
             f"The population prior is the tuning population's mean P(idle) per slot.\n")
    L.append("## Calibration of P(idle), next 24 h\n")
    L.append("| Method | Brier | Log loss | ECE |")
    L.append("|---|---|---|---|")
    for m in ("prior", "pooled", "beta_dow", "gbdt"):
        c = S["test"].get(m, {}).get("calibration")
        if c:
            L.append(f"| {NAMES[m]} | {_f(c['brier'], 4)} | {_f(c['log_loss'], 4)} | {_f(c['ece'], 4)} |")
    L.append("")
    L.append("Per archetype, Brier / log loss:\n")
    L.append("| Archetype | prior only | no day-of-week | **ships** | GBDT |")
    L.append("|---|---|---|---|---|")
    for a in ar.ARCHETYPES:
        cells = []
        for m in ("prior", "pooled", "beta_dow", "gbdt"):
            c = S["test"].get(m, {}).get("by_archetype", {}).get(a)
            cells.append("n/a" if not c else f"{_f(c['brier'], 3)} / {_f(c['log_loss'], 3)}")
        L.append(f"| {a} | " + " | ".join(cells) + " |")
    L.append("")
    L.append("Reliability of the shipped model:\n")
    L.append("| Predicted | Slots | Mean predicted | Observed idle rate |")
    L.append("|---|---|---|---|")
    for b in S["test"]["beta_dow"]["calibration"]["reliability"]:
        L.append(f"| {b['bin'][0]:.1f}-{b['bin'][1]:.1f} | {b['n']} | {_f(b['mean_p'])} | {_f(b['observed'])} |")
    L.append("")
    L.append("## Windows, scored as the shifts they would produce\n")
    L.append(f"For each night the simulated user lays the phone down for the night at the first slot inside the "
             f"window that starts {S.get('arm_run_slots', 8) * 15 // 60} or more idle hours (an evening lull does not "
             f"arm a Night Shift); the shift then runs until the window ends (**completed**, counts for the streak) "
             f"or until the first busy slot (a pickup breaks it). **Dark hours** = the idle time the rig ran; "
             "**completed dark hours** counts only completed shifts. **Coverage** = dark hours over the next "
             "24 h's longest idle block. **End error** = window end minus that block's end (positive: the window "
             "was still open when the user woke).\n")
    L.append("| Method | Window | Completed | Dark hours | Completed dark hours | Coverage | Median end error | "
             "Mean window |")
    L.append("|---|---|---|---|---|---|---|---|")
    for m in ("fixed_23_07", "yesterday", "prior", "pooled", "beta_dow", "gbdt"):
        w = S["test"].get(m, {}).get("window")
        if not w:
            continue
        L.append(f"| {NAMES[m]} | {_p(w['has'])} | {_p(w['completed'])} | {_f(w['dark_h'], 2)} h | "
                 f"{_f(w['completed_dark_h'], 2)} h | {_p(w['coverage'])} | {_f(w.get('end_err_min_median'), 0)} min | "
                 f"{_f(w['hours'], 1)} h |")
    L.append("")
    L.append("Shipped model, by archetype (auto-arm = zero-tap arming, only when every slot's lower bound clears "
             "the bar):\n")
    L.append("| Archetype | Completed | Dark hours | Completed dark hours | Coverage | Median end error | "
             "Auto-armed nights | Auto-armed and completed |")
    L.append("|---|---|---|---|---|---|---|---|")
    for a in ar.ARCHETYPES:
        w = S["test"]["beta_dow"]["window_by_archetype"][a]
        au = S["test"]["beta_dow"]["auto_arm"][a]
        L.append(f"| {a} | {_p(w['completed'])} | {_f(w['dark_h'], 2)} h | {_f(w['completed_dark_h'], 2)} h | "
                 f"{_p(w['coverage'])} | {_f(w.get('end_err_min_median'), 0)} min | {au['auto_armed']}/{au['nights']} | "
                 f"{_p(au['completed'])} |")
    L.append("")
    L.append("## Cold start (shipped parameters)\n")
    L.append("| Days of history | Brier | Log loss | Window | Completed | Dark hours | Completed dark hours |")
    L.append("|---|---|---|---|---|---|---|")
    for r in S["cold_start"]:
        L.append(f"| {r['days_of_history']} | {_f(r['brier'], 4)} | {_f(r['log_loss'], 4)} | {_p(r['has'])} | "
                 f"{_p(r['completed'])} | {_f(r['dark_h'], 2)} h | {_f(r['completed_dark_h'], 2)} h |")
    L.append("")
    n = S["night_only"]
    L.append("## Robustness: the app only watches 20:00-10:00\n")
    L.append(f"Slots outside 20:00-10:00 are unobserved, as if the app were alive only around shifts (scored on "
             f"what the phone really did). Next-24 h Brier {_f(n['calibration']['brier'], 4)}, log loss "
             f"{_f(n['calibration']['log_loss'], 4)} (daytime falls back to the prior); completed "
             f"{_p(n['window']['completed'])}, {_f(n['window']['dark_h'], 2)} dark hours, "
             f"{_f(n['window']['completed_dark_h'], 2)} completed dark hours per night.\n")
    L.append("## Tuning grid (tuning population, top 8 by log loss)\n")
    L.append("| Half-life (days) | k0 | k1 | k2 | Kernel | Log loss | Brier |")
    L.append("|---|---|---|---|---|---|---|")
    for g in sorted(S["grid"], key=lambda g: g["log_loss"])[:8]:
        L.append(f"| {g['half_life_days']} | {g['k0']} | {g['k1']} | {g['k2']} | {g['kernel']} | "
                 f"{_f(g['log_loss'], 4)} | {_f(g['brier'], 4)} |")
    L.append("")
    taus = [r for r in S["window_grid"] if "tau" in r]
    L.append("Window rule (tuning population; chosen by completed dark hours per night):\n")
    L.append("| Rule | tau | gamma | Completed | Dark hours | Completed dark hours | Mean window |")
    L.append("|---|---|---|---|---|---|---|")
    for r in taus:
        L.append(f"| {r['rule']} | {r['tau']} | {r['gamma'] if r['rule'] == 'survival' else '-'} | {_p(r['completed'])} | "
                 f"{_f(r['dark_h'], 2)} h | {_f(r['completed_dark_h'], 2)} h | {_f(r['hours'], 1)} h |")
    L.append("")
    aa = [r for r in S["window_grid"] if "auto_arm" in r][0]
    target = S.get("auto_arm_completion_target", 0.85)
    L.append("Auto-arm bar (tuning population): " + "; ".join(
        f"{b['bar']}: {b['auto_nights']} nights, completed {_p(b['completed'])}" for b in aa["auto_arm"]) +
             f". Chosen: the lowest bar whose auto-armed shifts completed on >= {_p(target, 0)} of at least 10 "
             f"nights ({aa['chosen_bar']}; 1.0 would mean auto-arm off).\n")
    return "\n".join(L) + "\n"
