package xyz.headsdown.surface.haptics

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool

/**
 * The audible arm thunk for phones whose motor cannot compose primitives.
 *
 * The sound (`res/raw/hd_thunk.wav`, 160 ms, 22.05 kHz mono) is generated by code in this
 * repository and dedicated to the public domain; see `surface/haptics/SOUNDS.md`. It is played
 * as a sonification sound, so the system's silent/vibrate modes and Do Not Disturb apply, and
 * [Haptics] additionally only plays it when the ringer is in normal mode.
 */
class ThunkSound(context: Context, private val volume: Float = DEFAULT_VOLUME) : AutoCloseable {

    private val pool: SoundPool = SoundPool.Builder()
        .setMaxStreams(1)
        .setAudioAttributes(
            AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_ASSISTANCE_SONIFICATION)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build(),
        )
        .build()

    @Volatile private var loaded = false
    @Volatile private var playWhenLoaded = false

    init {
        // One sound per pool, so any successful load is the thunk.
        pool.setOnLoadCompleteListener { _, _, status ->
            if (status == 0) {
                loaded = true
                if (playWhenLoaded) {
                    playWhenLoaded = false
                    play()
                }
            }
        }
    }

    private val soundId: Int = pool.load(context, R.raw.hd_thunk, 1)

    /** Plays now, or as soon as the (asynchronous) load completes. */
    fun play() {
        if (!loaded) {
            playWhenLoaded = true
            return
        }
        pool.play(soundId, volume, volume, 1, 0, 1f)
    }

    override fun close() = pool.release()

    private companion object {
        /** Bedside-quiet: loud enough to confirm "the rig is down", not to wake anyone. */
        const val DEFAULT_VOLUME = 0.6f
    }
}
