/**
 * OpenAPI 3.1 description of the public read API, served at /openapi.json. The test suite
 * validates live responses against these schemas and checks that every served route is
 * documented (test/api.test.ts).
 */
import { HAUL_MAX_ROUNDS } from "../metrics/haul.ts";

const str = { type: "string" } as const;
const int = { type: "integer" } as const;
const num = { type: "number" } as const;
const bool = { type: "boolean" } as const;
const u64 = { type: "string", pattern: "^[0-9]{1,20}$", description: "u64 as a decimal string (exact)" } as const;
const nullable = (s: object) => ({ oneOf: [s, { type: "null" }] });
const ref = (name: string) => ({ $ref: `#/components/schemas/${name}` });
/** Object whose `properties` are all required, plus `optional` ones. */
const obj = (properties: Record<string, unknown>, optional: Record<string, unknown> = {}) => ({
  type: "object",
  required: Object.keys(properties),
  properties: { ...properties, ...optional },
});
const arr = (items: unknown) => ({ type: "array", items });

const tzParam = {
  name: "tz",
  in: "query",
  required: false,
  description: "UTC offset in minutes for night/hour bucketing (default: the server's NIGHT_TZ_OFFSET_MINUTES, 60 = WAT).",
  schema: { type: "integer", minimum: -720, maximum: 840 },
};
const daysParam = {
  name: "days",
  in: "query",
  required: false,
  description: "Window length in days ending at `asOf` (1-90, default 7).",
  schema: { type: "integer", minimum: 1, maximum: 90 },
};

/** u64 as a JSON number when exact (<= 2^53), else a decimal string (contract B). */
const u64n = { oneOf: [{ type: "integer", minimum: 0 }, { type: "string", pattern: "^[0-9]{1,20}$" }], description: "u64: a JSON number up to 2^53, a decimal string above" } as const;
const rigParam = { name: "rig", in: "path", required: true, description: "Rig PDA (base58)", schema: { type: "string", pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$" } };
const errorQuery = {
  name: "error",
  in: "query",
  required: false,
  description: "Skip code: decimal, 0x-hex (e.g. 0x2560000e), or a name (StaleHeartbeat, LeaseExpired, MessageMismatch, ...).",
  schema: { type: "string" },
};
const rigQuery = { name: "rig", in: "query", required: false, description: "Only this rig (base58).", schema: { type: "string" } };

const envelope = (data: unknown) => ({
  "200": {
    description: "OK",
    headers: { "X-HeadsDown-Dataset": { schema: str, description: "mainnet | devnet | localnet | simulated" } },
    content: {
      "application/json": {
        schema: obj({ dataset: ref("Dataset"), asOf: int, generatedAt: str, data }),
      },
    },
  },
  "400": { description: "Invalid query parameter", content: { "application/json": { schema: ref("Error") } } },
});

const haulResponses = {
  "200": {
    description: "HaulSummary (contract B). Not enveloped: the dataset is in X-HeadsDown-Dataset and `simulated`.",
    headers: {
      "X-HeadsDown-Dataset": { schema: str },
      "X-HeadsDown-Haul-Checks": {
        schema: str,
        description:
          "dark=match|mismatch(n); sol-returned=exact|approx; deploys=match|mismatch, then `; rounds=first N of M` only when the shift spans more " +
          "rounds than a haul lists.",
      },
    },
    content: { "application/json": { schema: { $ref: "#/components/schemas/HaulSummary" } } },
  },
  "400": { description: "Invalid rig or shift_id", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
  "404": {
    description: "No finished shift, or the haul is not final yet (Retry-After set).",
    headers: { "Retry-After": { schema: int } },
    content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } },
  },
};

const csv = (description: string, params: unknown[]) => ({
  get: {
    summary: description,
    parameters: params,
    responses: {
      "200": {
        description: "RFC 4180 CSV. Every row starts with the dataset name; simulated files are named SIMULATED-*.",
        content: { "text/csv": { schema: str } },
      },
    },
  },
});

export const openApiDocument = {
  openapi: "3.1.0",
  info: {
    title: "Heads Down public traction API",
    version: "1.3.0",
    description:
      "Read-only metrics about Heads Down rigs, computed from on-chain data only: heads_down v1.3 program events and instruction data, " +
      "ORE DeployEvents whose signer is the Heads Down Executor PDA, heads_down accounts, ORE ResetEvents and ORE Round accounts. " +
      "Every metric carries `evidence` (transactions/accounts with explorer links) so it can be checked on chain. A server is bound to ONE " +
      "dataset; when `dataset.simulated` is true, all numbers are generated by the indexer's deterministic simulator and no explorer links are given. " +
      "Responses are wrapped in an envelope `{dataset, asOf, generatedAt, data}`, except the haul routes, whose body is the HaulSummary of " +
      "shared contract B itself (the dataset is in the `X-HeadsDown-Dataset` header and the `simulated` field).",
    license: { name: "MIT" },
  },
  paths: {
    "/v1/health": {
      get: {
        summary: "Liveness and ingest health: when the last ingest pass finished and whether it succeeded (decode problems are counted, never hidden).",
        responses: envelope(ref("Health")),
      },
    },
    "/v1/summary": { get: { summary: "Headline traction numbers with evidence.", parameters: [tzParam], responses: envelope(ref("Summary")) } },
    "/v1/cohorts": { get: { summary: "D1/D7/D14 retention by first-shift night.", parameters: [tzParam], responses: envelope(ref("CohortReport")) } },
    "/v1/share-by-hour": {
      get: { summary: "Heads Down share of unique ORE miners per round, by hour of day.", parameters: [tzParam, daysParam], responses: envelope(ref("ShareByHour")) },
    },
    "/v1/digs/recent": {
      get: {
        summary: "Most recent digs (RigDug paired with its ORE DeployEvent).",
        parameters: [{ name: "limit", in: "query", required: false, schema: { type: "integer", minimum: 1, maximum: 200 } }],
        responses: envelope(arr(ref("FeedItem"))),
      },
    },
    "/v1/skips": {
      get: {
        summary: "RigSkipped events, newest first, with each code's name and plain meaning, plus a histogram by code (for the rig filter, ignoring the error filter and pagination).",
        parameters: [
          rigQuery,
          errorQuery,
          { name: "limit", in: "query", required: false, schema: { type: "integer", minimum: 1, maximum: 500 } },
          { name: "cursor", in: "query", required: false, description: "`nextCursor` of the previous page.", schema: { type: "string" } },
        ],
        responses: envelope(ref("Skips")),
      },
    },
    "/v1/rigs/{rig}/haul/latest": {
      get: {
        summary: "Morning haul of the rig's most recent finished shift (shared contract B). The body is the HaulSummary itself, not the envelope.",
        description:
          "404 when the rig has no finished shift, or when the shift ended but its haul is not final yet (then `Retry-After` is set): every round it dug " +
          "must have been reset by ORE, and so must its end round while the shift is less than 30 minutes old. " +
          "ORE mined is ORE's checkpoint arithmetic on the rig's own DeployEvents and each round's outcome (Round account, else ResetEvent): unrefined, before ORE's 10% refining fee. " +
          "effective_lamports_per_ore = (SOL placed - SOL returned + fees) x 10^11 / ore_mined_atoms, rounded up. SOL returned is exact when the Round account was read " +
          "(header X-HeadsDown-Haul-Checks says `sol-returned=exact`), else losing squares use 89.1% (within 2 lamports per square). explorer links are null for simulated data. " +
          `\`rounds\` lists every round from start_round to end_round, up to ${HAUL_MAX_ROUNDS}: a shift left open for longer lists its first ${HAUL_MAX_ROUNDS} rounds, and every total still covers the whole shift.`,
        parameters: [rigParam],
        responses: haulResponses,
      },
    },
    "/v1/rigs/{rig}/haul/{shift_id}": {
      get: {
        summary: "Morning haul of one finished shift (shared contract B).",
        parameters: [rigParam, { name: "shift_id", in: "path", required: true, schema: { type: "string", pattern: "^[0-9]{1,20}$" } }],
        responses: haulResponses,
      },
    },
    "/v1/rigs/{rig}/shifts": {
      get: { summary: "The rig's finished shifts, newest first (for a shift picker).", parameters: [rigParam], responses: envelope(ref("RigShifts")) },
    },
    "/v1/milestones": { get: { summary: "ORE matched-prize milestones (docs/ORE.md section 9) against measured values.", parameters: [tzParam], responses: envelope(ref("Milestones")) } },
    "/v1/skr/summary": {
      get: {
        summary:
          "Totals of the SKR features (INTERFACE v1.2): Stack tables, Focus Bonds, Gift a Rig and the Bury auction. Counts and sums of the " +
          "program's own events; amounts are base units (SKR 6 decimals, ORE 11, gifts in lamports).",
        responses: envelope(ref("SkrSummary")),
      },
    },
    "/v1/export/rounds.csv": csv("Per ORE round: total miners (ResetEvent), Heads Down miners (DeployEvents), share, SOL, verifying signatures.", [daysParam]),
    "/v1/export/digs.csv": csv("Every dig in the window with its transaction signature.", [daysParam]),
    "/v1/export/skips.csv": csv("Every RigSkipped in the window: signature, rig, round, code (decimal and hex), name and plain meaning.", [rigQuery, errorQuery, daysParam]),
    "/v1/export/monthly.csv": csv("Monthly milestone report (rigs, Seeker rigs, nightly actives, rounds dug, SOL, ORE mined/bought/buried).", [tzParam]),
    "/openapi.json": { get: { summary: "This document.", responses: { "200": { description: "OpenAPI 3.1", content: { "application/json": { schema: { type: "object" } } } } } } },
  },
  components: {
    schemas: {
      Error: obj({ error: str }),
      Dataset: obj({
        name: { type: "string", enum: ["mainnet", "devnet", "localnet", "simulated"] },
        simulated: bool,
        programId: str,
        executorPda: str,
        simSeed: nullable(str),
      }),
      Evidence: obj({ label: str, kind: { type: "string", enum: ["tx", "account"] }, id: str, url: nullable(str) }),
      SkrSummary: obj({
        stack: obj({
          tablesOpened: int, seatsJoined: int, skrBonded: u64, tablesSettled: int, seatsSettled: int, finishers: int,
          skrToFinishers: u64, skrToBury: u64, checkinsCounted: int, checkinsRefused: int, payouts: int, skrPaidOut: u64,
          refunds: int, skrRefunded: u64,
        }),
        focusBond: obj({ locked: int, skrLocked: u64, released: int, skrReleased: u64, forfeited: int, skrForfeited: u64 }),
        gift: obj({
          created: int, lamportsCreated: u64, createdForSeeker: int, claimed: int, lamportsClaimed: u64, claimedBySeeker: int,
          refunded: int, lamportsRefunded: u64,
        }),
        bury: obj({
          lots: int, skrIn: u64, skrFromStack: u64, skrFromBonds: u64, sales: int, skrSold: u64, orePaid: u64, oreBurned: u64,
          oreToStakers: u64, lotSkr: nullable(u64), lastPrice: nullable(u64), startPrice: nullable(u64), startSlot: nullable(u64),
        }),
        units: obj({ skrDecimals: int, oreDecimals: int }),
      }),
      Health: obj({
        status: { type: "string", enum: ["ok"] },
        txs: int,
        failedTxs: int,
        truncatedTxs: int,
        lastSlot: {
          ...nullable(int),
          description:
            "Slot of the newest stored transaction (one that names the heads_down program or its Executor PDA), not the chain's slot: null before " +
            "the first one, and it stands still whenever no such transaction lands. To see whether ingestion is running, use lastPollAt and lastPollOk.",
        },
        lastBlockTime: { ...nullable(int), description: "Block time (unix seconds) of the newest stored transaction; null like lastSlot." },
        lastPollAt: {
          ...nullable(int),
          description:
            "Unix seconds at which the last ingest pass finished, whether it succeeded or failed. A pass runs every INGEST_INTERVAL_S over the " +
            "configured sources: the RPC poll when RPC_URL is set, and api.ore.com. Null when no pass has finished for this dataset " +
            "(always for the simulated dataset). Compare it with the envelope's asOf: a value that stops advancing means ingestion has stopped.",
        },
        lastPollOk: {
          ...nullable(bool),
          description: "Whether that pass succeeded. False while, for example, the RPC is down, out of credits or on another cluster; the reason is in the server log only.",
        },
        lastOkPollAt: { ...nullable(int), description: "Unix seconds at which the last successful pass finished; null if none has." },
        problems: arr(obj({ code: str, count: int })),
      }),
      Summary: obj({
        asOf: int,
        tzOffsetMinutes: int,
        lastCompleteNight: nullable(str),
        rigs: obj({
          total: int,
          seeker: int,
          guest: int,
          closed: int,
          basis: { type: "string", enum: ["lifecycle", "accounts", "events"] },
          everRegistered: nullable(int),
          crossCheck: obj({ accounts: nullable(int), accountsSeeker: nullable(int), matches: nullable(bool) }),
          evidence: arr(ref("Evidence")),
        }),
        nightlyActive: obj({
          lastNight: nullable(str),
          rigs: int,
          peak: int,
          series: arr(obj({ night: str, rigs: int, seeker: int })),
          evidence: arr(ref("Evidence")),
        }),
        darkHours: obj({
          hours: num,
          darkRounds: u64,
          roundSeconds: num,
          roundSecondsBasis: { type: "string", enum: ["measured", "fallback"] },
          shiftsEnded: int,
          evidence: arr(ref("Evidence")),
        }),
        roundsDug: obj({ rigRounds: int, distinctRounds: int, evidence: arr(ref("Evidence")) }),
        solDeployed: obj({ lamports: u64, oreDeployEventLamports: u64, consistent: bool, evidence: arr(ref("Evidence")) }),
        ore: obj({
          mined: obj({ amount: u64, digsPendingRound: int, basis: str, evidence: arr(ref("Evidence")) }),
          bought: obj({ amount: { type: "null" }, status: { type: "string", enum: ["not_shipped"] }, note: str }),
          buried: obj({ amount: { type: "null" }, status: { type: "string", enum: ["not_shipped"] }, note: str }),
        }),
        gate: obj({
          openRate: nullable(num),
          opened: int,
          closedByCostGate: int,
          digShareOfDarkRounds: nullable(num),
          evidence: arr(ref("Evidence")),
        }),
        skips: arr(obj({ code: int, name: str, range: ref("ErrorRange"), label: str, count: int })),
        crankers: obj({ distinct: int, thirdParty: nullable(int) }),
        programPaused: nullable(bool),
        consistency: obj({
          digsWithoutDeploy: int,
          deploysWithoutDig: int,
          lamportsMismatch: int,
          roundsDugExceedsDark: int,
          seekerTierWithoutSeat: int,
          hdMinersExceedTotal: int,
        }),
      }),
      CohortReport: obj({
        lastCompleteNight: nullable(str),
        cohorts: arr(obj({ cohort: str, size: int, cells: arr(obj({ day: int, retained: nullable(int), rate: nullable(num), mature: bool })) })),
        average: arr(obj({ day: int, rate: nullable(num), cohorts: int, rigs: int })),
      }),
      ShareByHour: obj({
        tzOffsetMinutes: int,
        windowDays: int,
        from: int,
        to: int,
        rounds: int,
        roundsWithHd: int,
        meanShare: nullable(num),
        hours: arr(
          obj({
            hour: int,
            rounds: int,
            roundsWithHd: int,
            meanShare: nullable(num),
            maxShare: nullable(num),
            meanHdMiners: nullable(num),
            meanTotalMiners: nullable(num),
            peak: nullable(
              obj({
                roundId: u64,
                share: num,
                hdMiners: int,
                totalMiners: u64,
                resetSignature: nullable(str),
                sampleDig: nullable(str),
                resetUrl: nullable(str),
                digUrl: nullable(str),
              }),
            ),
          }),
        ),
      }),
      FeedItem: obj({
        signature: str,
        blockTime: nullable(int),
        rig: str,
        authority: nullable(str),
        tier: nullable(int),
        roundId: u64,
        lamports: u64,
        squares: int,
        emaEv: u64,
        txUrl: nullable(str),
        rigUrl: nullable(str),
      }),
      ErrorRange: { type: "string", enum: ["heads_down", "p256-introspect", "sgt-verify", "builtin", "unknown"] },
      Skips: obj({
        filter: obj({ rig: nullable(str), error: nullable(int) }),
        total: int,
        histogram: arr(obj({ code: int, name: str, range: ref("ErrorRange"), label: str, count: int })),
        items: arr(
          obj({ signature: str, slot: int, blockTime: nullable(int), rig: str, roundId: u64, error: int, name: str, range: ref("ErrorRange"), label: str, txUrl: nullable(str) }),
        ),
        nextCursor: nullable(str),
      }),
      RigShifts: obj({
        rig: str,
        shifts: arr(obj({ shiftId: u64, endedAt: nullable(int), darkRounds: u64, roundsDug: u64, reason: int, mode: nullable(int), signature: str })),
      }),
      HaulSummary: obj({
        rig: str,
        shift_id: u64n,
        mode: { type: "string", enum: ["night", "day", "focus_only"] },
        start_ts: int,
        end_ts: int,
        start_round: u64n,
        end_round: u64n,
        rounds: {
          ...arr(
            obj({
              round_id: u64n,
              dark: bool,
              dug_mask: { type: "integer", minimum: 0, maximum: 33554431 },
              winning_square: nullable({ type: "integer", minimum: 0, maximum: 24 }),
              motherlode: bool,
              split: bool,
            }),
          ),
          maxItems: HAUL_MAX_ROUNDS,
        },
        dark_rounds: u64n,
        rounds_dug: u64n,
        sol_placed_lamports: u64n,
        fees_lamports: u64n,
        ore_mined_atoms: u64,
        // Not bounded by u64: a shift that mined only a few atoms of ORE divides its cost by almost nothing.
        effective_lamports_per_ore: nullable({ type: "string", pattern: "^[0-9]{1,40}$", description: "non-negative integer as a decimal string" }),
        market_lamports_per_ore: nullable(u64),
        market_source: nullable(str),
        streak_before: int,
        streak_after: int,
        break_reason: int,
        first_pickup_ts: { type: "null", description: "Not observable on chain; the phone fills it locally." },
        simulated: bool,
        explorer: obj({ shift_log: nullable(str), sample_digs: arr(str) }),
      }),
      Milestones: obj({
        tzOffsetMinutes: int,
        shareWindow: obj({ fromHour: int, toHour: int, nights: int }),
        milestones: arr(
          obj({
            id: { type: "string", enum: ["M1", "M2", "M3"] },
            title: str,
            deadline: str,
            metrics: arr(
              obj(
                { key: str, label: str, value: nullable(num), target: num, stretch: nullable(num), unit: { type: "string", enum: ["rigs", "share"] } },
                { note: str },
              ),
            ),
            manual: arr(str),
          }),
        ),
      }),
    },
  },
} as const;
