/**
 * OpenAPI 3.1 description of the public read API, served at /openapi.json. The test suite
 * validates live responses against these schemas and checks that every served route is
 * documented (test/api.test.ts).
 */
const str = { type: "string" } as const;
const int = { type: "integer" } as const;
const num = { type: "number" } as const;
const bool = { type: "boolean" } as const;
const u64 = { type: "string", pattern: "^[0-9]{1,20}$", description: "u64 as a decimal string (exact)" } as const;
const nullable = (s: object) => ({ oneOf: [s, { type: "null" }] });
const ref = (name: string) => ({ $ref: `#/components/schemas/${name}` });
/** Object whose `properties` are all required, plus `optional` ones. */
const obj = (properties: Record<string, unknown>, optional: Record<string, unknown> = {}) => ({
  type: "object",
  required: Object.keys(properties),
  properties: { ...properties, ...optional },
});
const arr = (items: unknown) => ({ type: "array", items });

const tzParam = {
  name: "tz",
  in: "query",
  required: false,
  description: "UTC offset in minutes for night/hour bucketing (default: the server's NIGHT_TZ_OFFSET_MINUTES, 60 = WAT).",
  schema: { type: "integer", minimum: -720, maximum: 840 },
};
const daysParam = {
  name: "days",
  in: "query",
  required: false,
  description: "Window length in days ending at `asOf` (1-90, default 7).",
  schema: { type: "integer", minimum: 1, maximum: 90 },
};

const envelope = (data: unknown) => ({
  "200": {
    description: "OK",
    headers: { "X-HeadsDown-Dataset": { schema: str, description: "mainnet | devnet | localnet | simulated" } },
    content: {
      "application/json": {
        schema: obj({ dataset: ref("Dataset"), asOf: int, generatedAt: str, data }),
      },
    },
  },
  "400": { description: "Invalid query parameter", content: { "application/json": { schema: ref("Error") } } },
});

const csv = (description: string, params: unknown[]) => ({
  get: {
    summary: description,
    parameters: params,
    responses: {
      "200": {
        description: "RFC 4180 CSV. Every row starts with the dataset name; simulated files are named SIMULATED-*.",
        content: { "text/csv": { schema: str } },
      },
    },
  },
});

export const openApiDocument = {
  openapi: "3.1.0",
  info: {
    title: "Heads Down public traction API",
    version: "1.0.0",
    description:
      "Read-only metrics about Heads Down rigs, computed from on-chain data only: heads_down program events, ORE DeployEvents " +
      "whose signer is the Heads Down Executor PDA, heads_down accounts, and ORE ResetEvents. Every metric carries `evidence` " +
      "(transactions/accounts with explorer links) so it can be checked on chain. A server is bound to ONE dataset; when " +
      "`dataset.simulated` is true, all numbers are generated by the indexer's deterministic simulator and no explorer links are given.",
    license: { name: "MIT" },
  },
  paths: {
    "/v1/health": { get: { summary: "Liveness and ingest health (decode problems are counted, never hidden).", responses: envelope(ref("Health")) } },
    "/v1/summary": { get: { summary: "Headline traction numbers with evidence.", parameters: [tzParam], responses: envelope(ref("Summary")) } },
    "/v1/cohorts": { get: { summary: "D1/D7/D14 retention by first-shift night.", parameters: [tzParam], responses: envelope(ref("CohortReport")) } },
    "/v1/share-by-hour": {
      get: { summary: "Heads Down share of unique ORE miners per round, by hour of day.", parameters: [tzParam, daysParam], responses: envelope(ref("ShareByHour")) },
    },
    "/v1/digs/recent": {
      get: {
        summary: "Most recent digs (RigDug paired with its ORE DeployEvent).",
        parameters: [{ name: "limit", in: "query", required: false, schema: { type: "integer", minimum: 1, maximum: 200 } }],
        responses: envelope(arr(ref("FeedItem"))),
      },
    },
    "/v1/milestones": { get: { summary: "ORE matched-prize milestones (docs/ORE.md section 9) against measured values.", parameters: [tzParam], responses: envelope(ref("Milestones")) } },
    "/v1/export/rounds.csv": csv("Per ORE round: total miners (ResetEvent), Heads Down miners (DeployEvents), share, SOL, verifying signatures.", [daysParam]),
    "/v1/export/digs.csv": csv("Every dig in the window with its transaction signature.", [daysParam]),
    "/v1/export/monthly.csv": csv("Monthly milestone report (rigs, Seeker rigs, nightly actives, rounds dug, SOL, ORE mined/bought/buried).", [tzParam]),
    "/openapi.json": { get: { summary: "This document.", responses: { "200": { description: "OpenAPI 3.1", content: { "application/json": { schema: { type: "object" } } } } } } },
  },
  components: {
    schemas: {
      Error: obj({ error: str }),
      Dataset: obj({
        name: { type: "string", enum: ["mainnet", "devnet", "localnet", "simulated"] },
        simulated: bool,
        programId: str,
        executorPda: str,
        simSeed: nullable(str),
      }),
      Evidence: obj({ label: str, kind: { type: "string", enum: ["tx", "account"] }, id: str, url: nullable(str) }),
      Health: obj({
        status: { type: "string", enum: ["ok"] },
        txs: int,
        failedTxs: int,
        truncatedTxs: int,
        lastSlot: nullable(int),
        lastBlockTime: nullable(int),
        problems: arr(obj({ code: str, count: int })),
      }),
      Summary: obj({
        asOf: int,
        tzOffsetMinutes: int,
        lastCompleteNight: nullable(str),
        rigs: obj({ total: int, seeker: int, guest: int, closed: int, basis: { type: "string", enum: ["accounts", "events"] }, evidence: arr(ref("Evidence")) }),
        nightlyActive: obj({
          lastNight: nullable(str),
          rigs: int,
          peak: int,
          series: arr(obj({ night: str, rigs: int, seeker: int })),
          evidence: arr(ref("Evidence")),
        }),
        darkHours: obj({
          hours: num,
          darkRounds: u64,
          roundSeconds: num,
          roundSecondsBasis: { type: "string", enum: ["measured", "fallback"] },
          shiftsEnded: int,
          evidence: arr(ref("Evidence")),
        }),
        roundsDug: obj({ rigRounds: int, distinctRounds: int, evidence: arr(ref("Evidence")) }),
        solDeployed: obj({ lamports: u64, oreDeployEventLamports: u64, consistent: bool, evidence: arr(ref("Evidence")) }),
        ore: obj({
          mined: obj({ amount: u64, digsPendingRound: int, basis: str, evidence: arr(ref("Evidence")) }),
          bought: obj({ amount: { type: "null" }, status: { type: "string", enum: ["not_shipped"] }, note: str }),
          buried: obj({ amount: { type: "null" }, status: { type: "string", enum: ["not_shipped"] }, note: str }),
        }),
        gate: obj({
          openRate: nullable(num),
          opened: int,
          closedByCostGate: int,
          digShareOfDarkRounds: nullable(num),
          evidence: arr(ref("Evidence")),
        }),
        skips: arr(obj({ code: int, name: str, count: int })),
        crankers: obj({ distinct: int, thirdParty: nullable(int) }),
        programPaused: nullable(bool),
        consistency: obj({
          digsWithoutDeploy: int,
          deploysWithoutDig: int,
          lamportsMismatch: int,
          roundsDugExceedsDark: int,
          seekerTierWithoutSeat: int,
          hdMinersExceedTotal: int,
        }),
      }),
      CohortReport: obj({
        lastCompleteNight: nullable(str),
        cohorts: arr(obj({ cohort: str, size: int, cells: arr(obj({ day: int, retained: nullable(int), rate: nullable(num), mature: bool })) })),
        average: arr(obj({ day: int, rate: nullable(num), cohorts: int, rigs: int })),
      }),
      ShareByHour: obj({
        tzOffsetMinutes: int,
        windowDays: int,
        from: int,
        to: int,
        rounds: int,
        roundsWithHd: int,
        meanShare: nullable(num),
        hours: arr(
          obj({
            hour: int,
            rounds: int,
            roundsWithHd: int,
            meanShare: nullable(num),
            maxShare: nullable(num),
            meanHdMiners: nullable(num),
            meanTotalMiners: nullable(num),
            peak: nullable(
              obj({
                roundId: u64,
                share: num,
                hdMiners: int,
                totalMiners: u64,
                resetSignature: nullable(str),
                sampleDig: nullable(str),
                resetUrl: nullable(str),
                digUrl: nullable(str),
              }),
            ),
          }),
        ),
      }),
      FeedItem: obj({
        signature: str,
        blockTime: nullable(int),
        rig: str,
        authority: nullable(str),
        tier: nullable(int),
        roundId: u64,
        lamports: u64,
        squares: int,
        emaEv: u64,
        txUrl: nullable(str),
        rigUrl: nullable(str),
      }),
      Milestones: obj({
        tzOffsetMinutes: int,
        shareWindow: obj({ fromHour: int, toHour: int, nights: int }),
        milestones: arr(
          obj({
            id: { type: "string", enum: ["M1", "M2", "M3"] },
            title: str,
            deadline: str,
            metrics: arr(
              obj(
                { key: str, label: str, value: nullable(num), target: num, stretch: nullable(num), unit: { type: "string", enum: ["rigs", "share"] } },
                { note: str },
              ),
            ),
            manual: arr(str),
          }),
        ),
      }),
    },
  },
} as const;
