"""Renders classifier/RESULTS.md from the metrics summary (generated; do not edit by hand)."""
from __future__ import annotations

from typing import Dict, List, Optional

from . import features as fx
from . import synth

SPLIT_TITLES = {
    "val": "validation (IID, picks thresholds)",
    "test_iid": "test, same conditions (IID)",
    "test_shift": "test, held-out conditions (shift)",
    "real_val": "real sensor lab, validation",
    "real_test": "real sensor lab, test",
}


def _pct(r: Optional[float], digits: int = 2) -> str:
    return "n/a" if r is None else f"{100 * r:.{digits}f}%"


def _rate(d: Dict, digits: int = 2) -> str:
    if not d or d.get("n", 0) == 0:
        return "n/a"
    lo, hi = d["ci95"]
    return f"{_pct(d['rate'], digits)} [{_pct(lo, 1)}, {_pct(hi, 1)}] (k={d['k']}/{d['n']})"


def summary(results: Dict, chosen: str, trig_stats: Dict, checks: Dict, cnn_info: Dict, sizes: Dict, real: Dict) -> Dict:
    return {
        "selected": chosen,
        "threshold": results[chosen]["threshold"],
        "threshold_logit": results[chosen]["threshold_logit"],
        "platt": results[chosen]["platt"],
        "results": results,
        "trigger_coverage": trig_stats,
        "checks": checks,
        "cnn": cnn_info,
        "sizes": sizes,
        "real": real,
        "features": list(fx.FEATURE_NAMES),
    }


def render(s: Dict) -> str:
    R = s["results"]
    ch = s["selected"]
    splits = [k for k in ("val", "test_iid", "test_shift", "real_val", "real_test") if k in R[ch]]
    L: List[str] = []
    L.append("# Pickup classifier: results (generated by `python -m classifier.train`)\n")
    if s.get("real"):
        L.append("> **Synthetic training data plus real sensor-lab sessions.** Only the `real sensor lab` rows "
                 "measure real-world behaviour, and only with as many windows as they show.\n")
    else:
        L.append("> **Synthetic data only** until real Redmi 14C sessions are recorded (see MODEL_CARD.md). "
                 "These numbers validate the pipeline and the physics model; they are **not** a measurement of "
                 "real-world accuracy.\n")
    sz = s["sizes"]
    L.append(f"Windows (all triggered by the production MotionTrigger): train {sz['train']}, validation {sz['val']}, "
             f"IID test {sz['test_iid']}, shift test {sz['test_shift']}. Label mix: 50% pickup, 25% bump, "
             "12.5% slide, 12.5% set-down.\n")
    L.append("The shift test uses surfaces (glass table, sofa), phone masses (<0.17 kg, >0.24 kg) and sensor "
             "profiles (40 Hz or 100 Hz delivery, 0.02-0.06 m/s^2 noise, 19-77 mm/s^2 quantization, 2-4 g range, "
             "larger bias and jitter) that never appear in training.\n")
    if s.get("real"):
        L.append(f"Real sensor-lab data: `{s['real']}`\n")

    L.append(f"## Selected model: `{ch}`\n")
    rc = R[ch]
    L.append(f"Verdict PICKUP iff the calibrated logit >= **{rc['threshold_logit']:.3f}** (P(pickup) >= "
             f"{rc['threshold']:.4f}). Rule applied: {rc['threshold_rule']}; validation gap between the 0.5% "
             f"lowest pickups and the 0.5% highest non-pickups = {rc['val_gap_logit']:.2f} logits. "
             f"Platt calibration a = {s['platt'][0]:.4f}, b = {s['platt'][1]:.4f}.\n")
    L.append("| Split | Pickup recall | Bump false-break | Slide false-break | Set-down false-break | All non-pickups |")
    L.append("|---|---|---|---|---|---|")
    for sp in splits:
        a = R[ch][sp]["at_threshold"]
        L.append(f"| {SPLIT_TITLES.get(sp, sp)} | {_rate(a['pickup_recall'])} | {_rate(a['bump_false_break'])} | "
                 f"{_rate(a['slide_false_break'])} | {_rate(a['set_down_false_break'])} | "
                 f"{_rate(a['all_negatives_false_break'])} |")
    L.append("")
    L.append("## All three models (each at its own validation threshold)\n")
    L.append("| Model | Threshold (logit) | Val gap (logits) | Val recall | Val false-break (all) | IID recall | "
             "IID bump FB | Shift recall | Shift bump FB | IID ECE | IID Brier |")
    L.append("|---|---|---|---|---|---|---|---|---|---|---|")
    for name, r in R.items():
        v, i, sh = r.get("val"), r.get("test_iid"), r.get("test_shift")
        def g(x, key):
            return _pct(x["at_threshold"][key]["rate"]) if x else "n/a"
        L.append(f"| {name}{' (selected)' if name == ch else ''} | {r['threshold_logit']:.3f} | "
                 f"{r['val_gap_logit']:.2f} | {g(v, 'pickup_recall')} | "
                 f"{g(v, 'all_negatives_false_break')} | {g(i, 'pickup_recall')} | {g(i, 'bump_false_break')} | "
                 f"{g(sh, 'pickup_recall')} | {g(sh, 'bump_false_break')} | "
                 f"{i['calibration']['ece']:.4f} | {i['calibration']['brier']:.4f} |")
    L.append("")
    for sp in ("test_iid", "test_shift"):
        if sp not in R[ch]:
            continue
        E = R[ch][sp]
        L.append(f"## Breakdown, {SPLIT_TITLES[sp]} (`{ch}`)\n")
        L.append("Per variant: for pickups the number is **recall**; for the others it is the **false-break rate**.\n")
        L.append("| Label / variant | Rate [95% CI] |")
        L.append("|---|---|")
        for k, d in E["by_variant"].items():
            L.append(f"| {k} | {_rate(d)} |")
        L.append("")
        for key, title in (("by_surface", "Surface"), ("by_mass", "Phone mass"), ("by_rate", "Delivery rate"),
                           ("by_noise", "Sensor noise")):
            L.append(f"| {title} | Pickup recall | Bump false-break | All non-pickups |")
            L.append("|---|---|---|---|")
            for k, d in E[key].items():
                L.append(f"| {k} | {_rate(d['pickup_recall'])} | {_rate(d['bump_false_break'])} | "
                         f"{_rate(d['negatives_false_break'])} |")
            L.append("")
    cal = R[ch]["test_iid"]["calibration"]
    L.append(f"## Calibration (`{ch}`, IID test)\n")
    L.append(f"ECE {cal['ece']:.4f}, Brier {cal['brier']:.4f}, log loss {cal['log_loss']:.4f}. P(pickup) is calibrated "
             "to this 50/50 synthetic mix; on the phone most motion windows at night are not pickups, so the "
             "prior-free threshold is what matters.\n")
    L.append("| Predicted bin | Windows | Mean predicted | Observed pickup rate |")
    L.append("|---|---|---|---|")
    for b in cal["reliability"]:
        mp = "n/a" if b["mean_p"] is None else f"{b['mean_p']:.3f}"
        ob = "n/a" if b["observed"] is None else f"{b['observed']:.3f}"
        L.append(f"| {b['bin'][0]:.1f}-{b['bin'][1]:.1f} | {b['n']} | {mp} | {ob} |")
    L.append("")
    L.append("## Trigger coverage (simulated events that produced a window)\n")
    L.append("The classifier only sees motions that fire the MotionTrigger (|a| off rest by 1.2 m/s^2, or gravity "
             "12 deg off). Gentle events below that never reach it; for pickups the FaceDownDetector (tilt > 40 deg) "
             "and the hard screen-on / unlock breaks still apply.\n")
    L.append("| Split | Label / variant | Triggered / simulated |")
    L.append("|---|---|---|")
    for sp, st in s["trigger_coverage"].items():
        for lab, d in st.items():
            for var, (k, n) in sorted(d.items()):
                L.append(f"| {sp} | {lab}/{var} | {k}/{n} ({_pct(k / n if n else None, 1)}) |")
    L.append("")
    c = s["checks"]
    L.append("## Export checks\n")
    for key, fname in (("cnn", "pickup_cnn.tflite"), ("selected", "pickup_model.tflite")):
        if f"tflite_{key}_bytes" in c:
            L.append(f"- `{fname}` ({c[f'tflite_{key}_model']}, float32, {c[f'tflite_{key}_bytes']} bytes) run in the "
                     f"LiteRT interpreter vs the float64 reference on the vector windows: max |logit difference| = "
                     f"{c[f'tflite_{key}_vs_float64_max_abs_logit']:.2e}.")
    L.append(f"- Vectorized evaluation path vs the loop-faithful reference (what Kotlin runs): max |logit "
             f"difference| = {c['vectorized_vs_loop_max_abs_logit']:.2e}.")
    L.append(f"- CNN training: {s['cnn']}.")
    L.append("")
    return "\n".join(L) + "\n"
