"""The sensor lab loader: both CSV layouts, label rules, and the committed synthetic sample."""
import io
import os

import numpy as np
import pytest

from classifier import sensorlab as sl

SAMPLE = os.path.join(os.path.dirname(__file__), "..", "data", "sample", "sensorlab-export-sample.csv")


@pytest.fixture(scope="module")
def export_text():
    buf = io.StringIO()
    sl.write_export(sl.synthetic_sessions(seed=3, per_session=2), buf, note="SYNTHETIC")
    return buf.getvalue()


def test_round_trip_keeps_samples_to_csv_precision(export_text):
    sessions = sl.read_sessions(io.StringIO(export_text))
    assert [s.session_id for s in sessions] == ["synthetic-pickup-01", "synthetic-bump-01", "synthetic-unlabeled-01"]
    src = sl.synthetic_sessions(seed=3, per_session=2)
    for s, (sid, label, wins, events) in zip(sessions, src):
        assert s.label == label and len(s.windows) == len(wins) and len(s.events) == len(events)
        for raw, w in zip(s.windows.values(), wins):
            assert raw.trigger_ns == w.trigger_ns and raw.t_ns == [int(t) for t in w.t_ns]
            assert np.max(np.abs(np.asarray(raw.acc) - w.acc)) <= 5e-6


def test_label_rules(export_text):
    wins, rep = sl.assign_labels(sl.read_sessions(io.StringIO(export_text)))
    by_session = {}
    for w in wins:
        by_session.setdefault(w.meta["session_id"], []).append(w.label)
    assert by_session["synthetic-pickup-01"] == ["pickup", "set_down", "pickup", "set_down"]
    assert by_session["synthetic-bump-01"] == ["bump", "bump"], "the pickup that ended the session is dropped"
    assert "synthetic-unlabeled-01" not in by_session
    assert rep.dropped["ended_by_user"] == 1 and rep.dropped["unlabeled_session"] == 1
    assert rep.relabeled["pickup->set_down"] == 2


def test_single_session_layout_and_garbage_rows():
    text = "\n".join([
        "# heads-down sensorlab v1 (debug build; accelerometer only)",
        "# session=20261001-230000 started_wall_ms=1 intended_label=bump",
        "# device=Xiaomi Redmi 14C sdk=34 sensor=accel rate_hz=50",
        sl.SESSION_COLUMNS,
        "event,,5,5,,,,session_start",
        "window_start,1,2000000000,,,,,",
        "sample,1,1000000000,1000100000,0.10000,-0.25000,-9.80665,",
        "sample,1,not-a-number,1,1,1,1,",
        "sample,1,2000000000,2000100000,1.00000,2.00000,-12.00000,",
        "sample,9,3000000000,3,1,1,1,",
        "window_end,1,2000000000,,,,,",
        "something,else",
    ])
    [s] = sl.read_sessions(io.StringIO(text))
    assert s.session_id == "20261001-230000" and s.label == "bump"
    assert s.meta.get("intended_label") == "bump"
    assert len(s.windows) == 1 and len(s.windows[1].t_ns) == 2 and s.events == [(5, "session_start")]


def test_truncated_and_unlabeled_windows_are_dropped():
    sessions = sl.read_sessions(io.StringIO("\n".join([
        sl.EXPORT_COLUMNS,
        "s1,pickup,window_start,1,5000000000,,,,,",
        "s1,pickup,sample,1,4000000000,4000000000,0,0,-9.8,",
        "s1,pickup,sample,1,5000000000,5000000000,0,0,-9.8,",
        "s1,pickup,window_end,1,5000000000,,,,,",
    ])))
    wins, rep = sl.assign_labels(sessions)
    assert wins == [] and rep.dropped["truncated"] == 1


def test_the_committed_sample_is_the_generator_output():
    """data/sample is regenerated with `python -m classifier.sensorlab make-sample`; it must not drift."""
    buf = io.StringIO()
    sl.write_export(sl.synthetic_sessions(), buf, note="SYNTHETIC SAMPLE generated by ml/foreman/classifier/sensorlab.py; not a real recording")
    with open(SAMPLE, "r", encoding="utf-8") as fh:
        assert fh.read() == buf.getvalue()
